# CMake generated Testfile for 
# Source directory: /home/comput-6/anim/Detection/submodule/glm/test/core
# Build directory: /home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test-core_cpp_constexpr "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_cpp_constexpr")
add_test(test-core_cpp_defaulted_ctor "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_cpp_defaulted_ctor")
add_test(test-core_force_aligned_gentypes "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_aligned_gentypes")
add_test(test-core_force_ctor_init "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_ctor_init")
add_test(test-core_force_explicit_ctor "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_explicit_ctor")
add_test(test-core_force_inline "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_inline")
add_test(test-core_force_pure "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_pure")
add_test(test-core_force_unrestricted_gentype "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_unrestricted_gentype")
add_test(test-core_force_xyzw_only "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_force_xyzw_only")
add_test(test-core_type_aligned "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_aligned")
add_test(test-core_type_cast "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_cast")
add_test(test-core_type_ctor "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_ctor")
add_test(test-core_type_int "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_int")
add_test(test-core_type_length "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_length")
add_test(test-core_type_mat2x2 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat2x2")
add_test(test-core_type_mat2x3 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat2x3")
add_test(test-core_type_mat2x4 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat2x4")
add_test(test-core_type_mat3x2 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat3x2")
add_test(test-core_type_mat3x3 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat3x3")
add_test(test-core_type_mat3x4 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat3x4")
add_test(test-core_type_mat4x2 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat4x2")
add_test(test-core_type_mat4x3 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat4x3")
add_test(test-core_type_mat4x4 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_mat4x4")
add_test(test-core_type_vec1 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_vec1")
add_test(test-core_type_vec2 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_vec2")
add_test(test-core_type_vec3 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_vec3")
add_test(test-core_type_vec4 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_type_vec4")
add_test(test-core_func_common "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_common")
add_test(test-core_func_exponential "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_exponential")
add_test(test-core_func_geometric "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_geometric")
add_test(test-core_func_integer "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_integer")
add_test(test-core_func_integer_bit_count "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_integer_bit_count")
add_test(test-core_func_integer_find_lsb "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_integer_find_lsb")
add_test(test-core_func_integer_find_msb "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_integer_find_msb")
add_test(test-core_func_matrix "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_matrix")
add_test(test-core_func_noise "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_noise")
add_test(test-core_func_packing "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_packing")
add_test(test-core_func_trigonometric "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_trigonometric")
add_test(test-core_func_vector_relational "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_vector_relational")
add_test(test-core_func_swizzle "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_func_swizzle")
add_test(test-core_setup_force_cxx98 "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_setup_force_cxx98")
add_test(test-core_setup_force_size_t_length "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_setup_force_size_t_length")
add_test(test-core_setup_message "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_setup_message")
add_test(test-core_setup_platform_unknown "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_setup_platform_unknown")
add_test(test-core_setup_precision "/home/comput-6/anim/Detection/cmake/glm-prefix/src/glm-build/test/core/test-core_setup_precision")
